### PR TITLE
Use `tracked` flag from OGN DDB to throw away no-tracking records

### PR DESCRIPTION
**Pull request by Turbo87**
see http://wiki.glidernet.org/opt-in-opt-out

/cc @snip

### CODE REVIEW

**Comment by kerel-fs** [comment]
Due to this patch only aircrafts which stated their explicit opt-in of the OGN tracking are displayed on <https://ogn.cloud>? :+1:

**Comment by Turbo87** [comment]
it's more of an opt-out. if they are registered in the OGN DDB and have activated the "don't show me in tracking but do support me for SAR" checkbox then the websocket gateway will discard their positions.

**Comment by kerel-fs** [comment]
Ok, I see, thanks for the clarification! I should've read the patch better...

**Comment by snip** [comment]
Thanks @Turbo87 for this.

**Pull request merged**
